export default {
    trending: [
        {
            id: '1asdf32',
            backgroundImg: "https://images4.alphacoders.com/854/thumbbig-854483.webp",
            cardImg: "https://images6.alphacoders.com/950/thumbbig-950030.webp",
            descriptoin: "The fourth season of the British-American animated comedy series The Amazing World of Gumball premiered on July 7, 2015 in the United States with the episode 'The Return'. It will consist of 40 eleven-minute episodes, as were the previous two seasons.",
            subTitle: "The Amazing World of Gumball - Season 4 (2015)",
            title: "Gumball",
            titelImg: "drama",
        },
        {
            id: 'KJSD98u23',
            backgroundImg: "https://images7.alphacoders.com/411/thumbbig-411309.webp",
            cardImg: "https://images.alphacoders.com/573/thumbbig-573870.webp",
            descriptoin: "In the year 10,191, the world is at war for control of the desert planet Dune—the only place where the time-travel substance 'Spice' can be found. But when one leader gives up control, it's only so he can stage a coup with some unsavory characters.",
            subTitle: "Dune (1984)",
            title: "Dune",
            titelImg: "drama",
        },
        {
            id: 'KJL9i32jlk',
            backgroundImg: "https://images8.alphacoders.com/117/thumbbig-1176007.webp",
            cardImg: "https://images7.alphacoders.com/117/thumbbig-1175946.webp",
            descriptoin: "Currently you are able to watch Young Sheldon - Season 1 streaming on fuboTV, DIRECTV, HBO Max, Spectrum On Demand, Paramount Plus, Paramount+ Amazon Channel or buy it as download on Apple iTunes, Google Play Movies, Vudu, Amazon Video, Microsoft Store.",
            subTitle: "Young Sheldon - Season 1 Sep 25 2017",
            title: "Young Sheldon",
            titelImg: "drama",
        },
        {
            id: 'ksdaljf93',
            backgroundImg: "https://images3.alphacoders.com/202/thumbbig-202849.webp",
            cardImg: "https://images3.alphacoders.com/258/thumbbig-258219.webp",
            descriptoin: "Brave is set in the mystical Scottish Highlands, where Mérida is the princess of a kingdom ruled by King Fergus and Queen Elinor. An unruly daughter and an accomplished archer, Mérida one day defies a sacred custom of the land and inadvertently brings turmoil to the kingdom. In an attempt to set things right, Mérida seeks out an eccentric old Wise Woman and is granted an ill-fated wish. Also figuring into Mérida’s quest — and serving as comic relief — are the kingdom’s three lords: the enormous Lord MacGuffin, the surly Lord Macintosh, and the disagreeable Lord Dingwall.",
            subTitle: "Brave (2012)",
            title: "Brave",
            titelImg: "drama",
        },
    ] ,
    originals: [
        {
            id: '823KJ8jdsd',
            backgroundImg: "https://images4.alphacoders.com/807/thumbbig-807426.webp",
            cardImg: "https://images.alphacoders.com/807/thumbbig-807425.webp",
            descriptoin: "A neurotic mid-20s suburbanite's convinced he's destined to be one of the greatest rappers of all time. Now he's got to prove it to everyone else.",
            subTitle: "Dave (2020)",
            title: "Dave",
            titelImg: "drama",
        },
        {
            id: '92klsd83F',
            backgroundImg: "https://images2.alphacoders.com/875/thumbbig-875980.webp",
            cardImg: "https://images2.alphacoders.com/881/thumbbig-881896.webp",
            descriptoin: "As the gang return to Jumanji to rescue one of their own, they discover that nothing is as they expect. The players will have to brave parts unknown and unexplored in order to escape the world’s most dangerous game.",
            subTitle: "The Next Level (2019)",
            title: "Jumanji",
            titelImg: "drama",
        },
        {   
            id: 'dsfk923',
            backgroundImg: "https://images6.alphacoders.com/807/thumbbig-807445.webp",
            cardImg: "https://images.alphacoders.com/112/thumbbig-1122155.webp",
            descriptoin: "Leonard Shelby is tracking down the man who raped and murdered his wife. The difficulty of locating his wife's killer, however, is compounded by the fact that he suffers from a rare, untreatable form of short-term memory loss. Although he can recall details of life before his accident, Leonard cannot remember what happened fifteen minutes ago, where he's going, or why.",
            subTitle: "Memento (2000)",
            title: "Memento",
            titelImg: "drama",
        },
        {
            id: "sdi2392",
            backgroundImg: "https://images5.alphacoders.com/417/thumbbig-417266.webp",
            cardImg: "https://images8.alphacoders.com/417/thumbbig-417267.webp",
            descriptoin: "A group of Hollywood actors and comedians face the apocalypse while at a party hosted by James Franco. With an impending water shortage and imminent danger outside their front door, the likes of Seth Rogan, Jonah Hill and Jay Baruchel try to form a survival plan. The film is an adaptation of the short film, Jay and Seth Versus the Apocalypse.",
            subTitle: "This Is the End (2013)",
            title: "This Is The End",
            titelImg: "drama",
        },
    ],
    newdisney: [
        {
            id: '02klc223',
            backgroundImg: "https://images5.alphacoders.com/771/thumbbig-771259.webp",
            cardImg: "https://images4.alphacoders.com/111/thumbbig-1118596.webp",
            descriptoin: "Sebastian and Mia are both struggling to achieve their dreams in Los Angeles. While Sebastian wants to indulge in his love of music, Mia is determined to become a successful actress. They form an unlikely bond and passionately push each other to reach their goals. Set in a colorful reality inspired by classic cinema, La La Land was written and directed by Damien Chazelle.",
            subTitle: "La La Land (2016)",
            title: "La La Land",
            titelImg: "drama",
        },
        {
            id: 'lsdo0238',
            backgroundImg: "https://wallpapershome.com/images/pages/pic_h/22641.jpg",
            cardImg: "https://wallpapershome.com/images/pages/ico_h/22642.jpeg",
            description: "Set in London, where gratification is only an app away, the story centers on Arabella, a carefree, self-assured Londoner with a group of great friends, a boyfriend in Italy, and a burgeoning writing career. But when her drink is spiked, she must question and rebuild every element of her life.",
            subTitle: "I May Destroy You (2020)",
            title: "I May Destroy You",
            titelImg: "drama",
        },
        {
            id: '32r4miw2',
            backgroundImg: "https://images5.alphacoders.com/327/thumbbig-327114.webp",
            cardImg: "https://images5.alphacoders.com/658/thumbbig-658319.webp",
            descriptoin: "Former Special Forces operative Wade Wilson is working as a mercenary. His life turns upside-down when a scientist disfigures his face and gives him accelerated healing abilities. With help from X-Men members Colossus and Negasonic Teenage Warhead, he must hunt down the man who changed his life forever. Filled with meta-comedy and fourth-wall breaks, the wisecracking Deadpool is played by Ryan Reynolds. The actor previously played an alternate version of the character in Wolverine: Origins.",
            subTitle: "Deadpool (2016)",
            title: "DeadPool",
            titelImg: "drama",
        },
        {
            id: 'Fe293d422',
            backgroundImg: "https://images5.alphacoders.com/637/thumbbig-637019.webp",
            cardImg: "https://images2.alphacoders.com/674/thumbbig-674137.webp",
            descriptoin: "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
            subTitle: "Pulp Fiction (1994)",
            title: "Pulp Fiction",
            titelImg: "drama",
        },
    ],
    recommended: [
        {
            id: 'kdf93213',
            backgroundImg: "https://images4.alphacoders.com/646/thumbbig-646889.webp",
            cardImg: "https://images6.alphacoders.com/771/thumbbig-771738.webp",
            descriptoin: "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
            subTitle: "The Godfather (1972))",
            title: "The Gadfather",
            titelImg: "drama",
        },
        {
            id: 'ksd8320',
            backgroundImg: "https://images5.alphacoders.com/637/thumbbig-637508.webp",
            cardImg: "https://images.alphacoders.com/635/thumbbig-635842.webp",
            descriptoin: "Mad Men is set in the 1960s, initially at the fictional Sterling Cooper advertising agency on Madison Avenue in New York City, and later at the newly created firm, Sterling Cooper Draper Pryce, located nearby in the Time-Life Building, at 1271 Avenue of the Americas. According to the show's pilot, the phrase mad men was a slang term coined in the 1950s by advertisers working on Madison Avenue to refer to themselves. The focal point of the series is Don Draper, creative director at Sterling Cooper and a founding partner at Sterling Cooper Draper Pryce, and the people in his life, both in and out of the office. The plot focuses on the business of the agencies as well as the personal lives of the characters, regularly depicting the changing moods and social mores of the United States in the 1960s.",
            subTitle: "MAD MEN - WATCH ONLINE: STREAMING, BUY OR RENT",
            title: "Mad Men",
            titelImg: "drama",
        },
        {
            id: 'sdi3l013',
            backgroundImg: "https://images5.alphacoders.com/730/thumbbig-730146.webp",
            cardImg: "https://images7.alphacoders.com/730/thumbbig-730065.webp",
            descriptoin: "Currently you are able to watch Don't Breathe streaming on fuboTV, DIRECTV, Spectrum On Demand. It is also possible to buy Don't Breathe on Apple iTunes, Google Play Movies, Vudu, Amazon Video, Microsoft Store, YouTube, Redbox, AMC on Demand, DIRECTV as download or rent it on Apple iTunes, Google Play Movies, Vudu, Amazon Video, Microsoft Store, YouTube, Redbox, AMC on Demand, DIRECTV online.",
            subTitle: "VIDEOS: TRAILERS, TEASERS, FEATURETTES",
            title: "Don't Breath",
            titelImg: "drama",
        },
        {
            id: 'akIO9887',
            backgroundImg: "https://images6.alphacoders.com/853/thumbbig-853375.webp",
            cardImg: "https://images3.alphacoders.com/178/thumbbig-178309.webp",
            descriptoin: "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard -- with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths -- and about the villain who's to blame.",
            subTitle: "Harry Potter and the Philosopher's Stone (2001)",
            title: "Harry Potter",
            titelImg: "drama",
        },
    ]
}